FROM streamsets/datacollector:3.7.2

USER root
RUN apk add --update --no-cache openssh sudo
USER sdc

#EXPOSE 18630

#COPY docker-entrypoint.sh /
#ENTRYPOINT ["/docker-entrypoint.sh"]
#CMD ["dc", "-exec"]
